# Generated by Django 4.2.7 on 2025-05-04 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary_type', models.CharField(choices=[('bert_gpt2', 'BERT & GPT-2'), ('gemini', 'Google Gemini')], default='bert_gpt2', max_length=20)),
                ('bert_summary', models.TextField(blank=True, null=True)),
                ('gpt2_summary', models.TextField(blank=True, null=True)),
                ('gemini_summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
