# Generated by Django 4.2.7 on 2025-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='current_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('ru', 'Russian'), ('pt', 'Portuguese')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='translated_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
