# Generated by Django 4.2.7 on 2025-05-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0003_alter_pdfdocument_current_language_imagedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedocument',
            name='analysis_source',
            field=models.CharField(choices=[('google_vision', 'Google Cloud Vision'), ('tesseract_ocr', 'Tesseract OCR'), ('ocr_description', 'OCR Description'), ('error', 'Error')], default='tesseract_ocr', help_text='Source of the image analysis', max_length=20),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='detected_objects',
            field=models.TextField(blank=True, help_text='Comma-separated list of detected objects', null=True),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='labels',
            field=models.TextField(blank=True, help_text='Comma-separated list of detected labels', null=True),
        ),
    ]
