# Generated by Django 4.2.7 on 2025-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='questions',
            field=models.TextField(blank=True, help_text='User questions related to the PDF', null=True),
        ),
    ]
