# Generated by Django 4.2.7 on 2025-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0006_pdfdocument_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='answers',
            field=models.TextField(blank=True, help_text='Answers to user questions related to the PDF', null=True),
        ),
    ]
