# Generated by Django 4.2.7 on 2025-05-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0007_pdfdocument_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedocument',
            name='current_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('ar', 'Arabic'), ('fa', 'Persian'), ('tr', 'Turkish')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='translated_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
