# Generated by Django 4.2.7 on 2025-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0008_imagedocument_current_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedocument',
            name='analysis_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence score of the analysis (0-1)'),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='analysis_data',
            field=models.JSONField(blank=True, help_text='Comprehensive analysis data', null=True),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='character_count',
            field=models.IntegerField(default=0, help_text='Number of characters extracted'),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='classification_data',
            field=models.JSONField(blank=True, help_text='Detailed classification results', null=True),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='color_type',
            field=models.CharField(blank=True, help_text='Color type description', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='edge_density',
            field=models.FloatField(default=0.0, help_text='Edge density in the image'),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Raw extracted text from image', null=True),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='faces_detected',
            field=models.IntegerField(default=0, help_text='Number of faces detected in the image'),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='image_height',
            field=models.IntegerField(default=0, help_text='Image height in pixels'),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='image_type',
            field=models.CharField(choices=[('general', 'General Image'), ('document', 'Document'), ('technical_diagram', 'Technical Diagram'), ('diagram', 'Diagram/Chart'), ('banner_or_poster', 'Banner/Poster'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='image_width',
            field=models.IntegerField(default=0, help_text='Image width in pixels'),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='ocr_config',
            field=models.TextField(blank=True, help_text='OCR configuration used (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='processing_variant',
            field=models.CharField(blank=True, help_text='Image processing variant used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='text_density',
            field=models.FloatField(default=0.0, help_text='Text density in the image'),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='text_quality',
            field=models.CharField(default='unknown', help_text='Quality assessment of extracted text', max_length=20),
        ),
        migrations.AddField(
            model_name='imagedocument',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Number of words extracted'),
        ),
        migrations.AlterField(
            model_name='imagedocument',
            name='summary',
            field=models.TextField(blank=True, help_text='Comprehensive image summary', null=True),
        ),
        migrations.AlterField(
            model_name='imagedocument',
            name='translated_summary',
            field=models.TextField(blank=True, help_text='Translated summary', null=True),
        ),
    ]
